//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Inputs/BlowerInputsActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BlowerInputsActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BlowerInputsActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BlowerInputsActions"",
    ""maps"": [
        {
            ""name"": ""Blower"",
            ""id"": ""e8628b71-609b-4460-8bd0-a833fae2f59e"",
            ""actions"": [
                {
                    ""name"": ""Blow"",
                    ""type"": ""Button"",
                    ""id"": ""ef22dee1-2a42-4c00-b77f-d9060162aeca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aspire"",
                    ""type"": ""Button"",
                    ""id"": ""b53e401a-d411-448e-9d05-72029c54fa3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveObject"",
                    ""type"": ""Button"",
                    ""id"": ""f557b33f-bf6f-44a4-8c9c-a1eabc63fe64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateObject"",
                    ""type"": ""Button"",
                    ""id"": ""042a7c09-767b-4d04-9551-6ddded012b60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""75420379-ee0d-41b0-846f-b163a59ea8be"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Blow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a6f17c-15e1-4d81-81fc-90d657f1c26e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Blow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""621148b6-d29f-4717-ae66-3944d88ff82a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Blow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d40ec7b2-2f66-43b3-9795-1d799833d8b4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Blow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18554290-073c-493f-a733-9cf353f77c0b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Blow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b5e26c9-2e8d-42d0-b9bc-83f6ef22dec0"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Aspire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b98745-5c58-4635-83a7-afde62b84c7c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aspire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7782cbbc-d5cd-41ef-9ce3-be5ad34075e3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Aspire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b15b2577-baa9-4328-a97a-d7d5312605e9"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Aspire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d57a534b-f280-422c-96d1-074620c5a5ca"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Aspire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d1b9b3-17ed-4469-a6a9-f4796c625473"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""SaveObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3522ef44-8a57-41b1-b9cc-228fabb3ec86"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9202af01-23e3-47a8-8586-a4b100650a07"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SaveObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c8ec46d-af21-47a8-8d94-481bf5f783d4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""RotateObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Blower
        m_Blower = asset.FindActionMap("Blower", throwIfNotFound: true);
        m_Blower_Blow = m_Blower.FindAction("Blow", throwIfNotFound: true);
        m_Blower_Aspire = m_Blower.FindAction("Aspire", throwIfNotFound: true);
        m_Blower_SaveObject = m_Blower.FindAction("SaveObject", throwIfNotFound: true);
        m_Blower_RotateObject = m_Blower.FindAction("RotateObject", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Blower
    private readonly InputActionMap m_Blower;
    private List<IBlowerActions> m_BlowerActionsCallbackInterfaces = new List<IBlowerActions>();
    private readonly InputAction m_Blower_Blow;
    private readonly InputAction m_Blower_Aspire;
    private readonly InputAction m_Blower_SaveObject;
    private readonly InputAction m_Blower_RotateObject;
    public struct BlowerActions
    {
        private @BlowerInputsActions m_Wrapper;
        public BlowerActions(@BlowerInputsActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Blow => m_Wrapper.m_Blower_Blow;
        public InputAction @Aspire => m_Wrapper.m_Blower_Aspire;
        public InputAction @SaveObject => m_Wrapper.m_Blower_SaveObject;
        public InputAction @RotateObject => m_Wrapper.m_Blower_RotateObject;
        public InputActionMap Get() { return m_Wrapper.m_Blower; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BlowerActions set) { return set.Get(); }
        public void AddCallbacks(IBlowerActions instance)
        {
            if (instance == null || m_Wrapper.m_BlowerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BlowerActionsCallbackInterfaces.Add(instance);
            @Blow.started += instance.OnBlow;
            @Blow.performed += instance.OnBlow;
            @Blow.canceled += instance.OnBlow;
            @Aspire.started += instance.OnAspire;
            @Aspire.performed += instance.OnAspire;
            @Aspire.canceled += instance.OnAspire;
            @SaveObject.started += instance.OnSaveObject;
            @SaveObject.performed += instance.OnSaveObject;
            @SaveObject.canceled += instance.OnSaveObject;
            @RotateObject.started += instance.OnRotateObject;
            @RotateObject.performed += instance.OnRotateObject;
            @RotateObject.canceled += instance.OnRotateObject;
        }

        private void UnregisterCallbacks(IBlowerActions instance)
        {
            @Blow.started -= instance.OnBlow;
            @Blow.performed -= instance.OnBlow;
            @Blow.canceled -= instance.OnBlow;
            @Aspire.started -= instance.OnAspire;
            @Aspire.performed -= instance.OnAspire;
            @Aspire.canceled -= instance.OnAspire;
            @SaveObject.started -= instance.OnSaveObject;
            @SaveObject.performed -= instance.OnSaveObject;
            @SaveObject.canceled -= instance.OnSaveObject;
            @RotateObject.started -= instance.OnRotateObject;
            @RotateObject.performed -= instance.OnRotateObject;
            @RotateObject.canceled -= instance.OnRotateObject;
        }

        public void RemoveCallbacks(IBlowerActions instance)
        {
            if (m_Wrapper.m_BlowerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBlowerActions instance)
        {
            foreach (var item in m_Wrapper.m_BlowerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BlowerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BlowerActions @Blower => new BlowerActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IBlowerActions
    {
        void OnBlow(InputAction.CallbackContext context);
        void OnAspire(InputAction.CallbackContext context);
        void OnSaveObject(InputAction.CallbackContext context);
        void OnRotateObject(InputAction.CallbackContext context);
    }
}
